apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-exec-pod
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: nginx-liveness-exec-pod
      image: busybox:latest

      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30;
          rm -rf /tmp/healthy; sleep 600;

      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      ports:
        - containerPort: 8080 #not really needed