apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness-pod
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: nginx-liveness-pod
      image: muzieh/liveness-probe-app:1.0
      livenessProbe:
        httpGet:
          path: /alive
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      ports:
        - containerPort: 8080 #not really needed